### ISSUE TITLE
Volume lowers between songs sometimes 

### ISSUE THREAD

**Issue by pkmccarthy** [LINVALE/RHEOS#1]
Peter,
Have you seen this behavior before? I thought I fixed it with a reboot but it's back..

while setting volume, the volume controls will fight me and lower the speakers… It takes a few iterations, and it stabilizes

and after song finishes, and during the start of the next song, you can literally watch the volume controls, go down whether you’re in group mode or not… It’s like they’re trying to get back to some original setting. I have tried closing all the HEOS apps, leaving it open, adjusting in both, but I cannot find a consistent scenario when this doesn’t /does  happen.

 right now I’m listening to speakers outside, and the last two songs have not had a volume drop, but just before then it did, and I had to reset to the higher volume

I have tried various combinations of the experimental settings for volume as well

**Comment by LINVALE** [comment]
Haven't seen the volume drop - not sure why that should occur.

There's a lot of communication between the Heos App and Roon going on when volumes are adjusted. On a fast stable network it works. If you have a poorer connection I can see this being slow.

Let me think if there's a way I can give you an option to decouple the 2-way immediate changes for volume control as an option perhaps?

**Comment by pkmccarthy** [comment]
So my issue was the fact that upon rebuild of the roon core image I did not have your extension enabled.  But since most of the data is there (upnp info) roon could still send music to the endpoints, just not control anything..  entirely a user issue (me) but something interesting to note when the app loses control.
