### ISSUE TITLE
Container (installed via extension manager) exits with uncaught exception

### ISSUE THREAD

**Issue by japz** [LINVALE/RHEOS#2]
I installed this extension via the Roon Extension Manager, but the container keeps restarting with the following error message

```Node.js v19.9.0
STARTING ROON
10.0.9.9,Linux,nas,linux,x64 0.6.5-17
STARTING HEOS
ROON PAIRED
No devices found
DISCOVERING DEVICES
GETTING PLAYERS
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "AWAITING CONNECTION".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

**Comment by LINVALE** [comment]
Sorry you are having trouble.

RHEOS is unable to identify any HEOS enabled devices on your network.  Could you give me some information on your set up, what devices you have and how they are connected please.

**Comment by japz** [comment]
Thank you for your response. I have two networks, `10.0.8.0/24` which my IoT devices sit on and `10.0.9.0/24` which my NAS (Synology) uses. I have set up an IGMP proxy and mDNS repeating between the networks so the devices should be discoverable.
I can see the Marantz amplifier from my HEOS app using my iPhone that sits on the `10.0.9.0/24` network.

I will do some more debugging and figure out how https://github.com/juliuscc/heos-api does the discovery

**Comment by LINVALE** [comment]
Thanks. As noted in the readme RHEOS only discovers devices on the same network. You are going to the correct place to explore - there's not been much activity on the heos-api repo recently. Please update if you are able to configure this to work. I dont have plans to support this at present.
