### ISSUE TITLE
Roon and Heos looses connection for control

### ISSUE THREAD

**Issue by rajeevan** [LINVALE/RHEOS#3]
Hello,

I'm using the latest (test) docker image, running in DietPi (Pi3B+).
I'm connecting to Marantz Cinema 70s and everything is working perfectly, It shows both zones in the Roon and so on...

What I noticed is that after some time playing music, I cannot control the Volume through Roon. Nothing happening, but the music is playing just fine.

I logged into extract log from Docker and I notice some errors about `NetworkError` and then some possible `MemoryLeak` on few occasion..

I paused the music and when I resumed again (All in Roon); it crashed and restated. When I press play again, I now have the control of Volume.

See attached log (truncated)...
[heos_log.txt](https://github.com/LINVALE/RHEOS/files/12254624/heos_log.txt)

Would be great if this can be fixed...

Edit: Heos Information:
```
Firmware
Version | 3400-8281-E054-8790
-- | --
-DTS Version | 3.90.50.82
```

Also, I cannot Pause/Play or do any control from HEOS. Nothing happening

Thanks

**Comment by LINVALE** [comment]
Thanks.

Am investigating- but think this is a result of network errors.

A restart will fix the issue - but I'd like to be able to detect and fix it m.

Please share any info.

Do try the latest version 0.7.0-1 which addresses several bugs and adds features. My goal is to increase stability and deal with  this type of issue you report. Sorry no specific fix yet.

**Comment by rajeevan** [comment]
Thanks, I'll update the new version tonight.

I'll report back after using a little time. Thanks
