### ISSUE TITLE
Please add supports for DSD format?

### ISSUE THREAD

**Issue by ProphetRush** [LINVALE/RHEOS#3]
Hi,
    Thank you for your hardwork, I can finally stream 24/192 music via Roon to my Marantz player. However, I found that the extension does not support DSD files, if I set to passthrough mode and plays a DSD file, there is no sound output. Can you add support for DSD files?

**Comment by LINVALE** [comment]
Ill see what can be done. I don't use the format but will explore.

**Comment by LINVALE** [comment]
DSD files are not supported by squeeze2upnp as far as I can tell. Sorry theres little I can do to help here.

You seem to have already discovered the new (experimental) "Pass Thru" setting which would be the only way i could see this working. I am assuming you have selected DSD on the Marantz Receiver - or that the player is HS2 as HS1 will not play DSD.

**Comment by ProphetRush** [comment]
> 
Thank you for your exploration. My Marantz Receiver supports DSD via DoP up to DSD128, I can play DSD files on my NAS Music Server directly from official HEOS App, so I am surprised that passthrough is not working haha, guess may be the file header issue considering the DoP is actually faked PCM stream? whatever...

**Comment by LINVALE** [comment]
Thanks.
I’ll take a look at ‘pass through’ in case there’s anything I can see that might be a problem.
Will let you know if I find anything for you to test!
Regards
Peter



Sent from Yahoo Mail for iPhone


On Sunday, January 29, 2023, 12:48 AM, Prophet Liao ***@***.***> wrote:






Thank you for your exploration. My Marantz Receiver supports DSD via DoP up to DSD128, I can play DSD files on my NAS Music Server directly from official HEOS App, so I am surprised that passthrough is not working haha, guess may be the file header issue considering the DoP is actually faked PCM stream? whatever...
