### ISSUE TITLE
runaway volume control

### ISSUE THREAD

**Issue by markpinis** [LINVALE/RHEOS#4]
[_roon-extension-rheos_logs.txt](https://github.com/LINVALE/RHEOS/files/13621462/_roon-extension-rheos_logs.txt)
[_roon-extension-rheos_logs(1).txt](https://github.com/LINVALE/RHEOS/files/13621463/_roon-extension-rheos_logs.1.txt)

**Comment by LINVALE** [comment]
Am closing this as it seems this is no longer an issue.
