### ISSUE TITLE
Docker container on Synology keeps crashing

### ISSUE THREAD

**Issue by MattRimkus** [LINVALE/RHEOS#5]
Hi, 

I only just found out about RHEOS and the possibility of running it on my Synology NAS... I managed to download the image via Container Manager and start it up with all setting on default (I created a shared folder Docker with a subfolder RHEOS).

Roon discovers the extension correctly but before I get the chance to configure it the container keeps crashing (log attached).

Unfortunately my knowledge in this area is quite rudimentary so I hope you can nudge me in the right direction.

I use a Synology DS423+ running DSM 7.2.1-69057 Update 4  and I'm trying to discover my new Marantz Stereo 70s.

KInd regards,
Matt

[rheos-roon-extension-rheos-1.csv](https://github.com/LINVALE/RHEOS/files/15067712/rheos-roon-extension-rheos-1.csv)

**Comment by LINVALE** [comment]
Please take a look at the community discussion.

Please share how you are running this on the Synology - which I don't officially support but others are using successfully.

Making sure you use network:host is key.

https://community.roonlabs.com/t/roon-extension-rheos-2-way-control-192hz-24bit-playback-and-grouping-on-denon-marantz-heos-devices-now-in-extension-manager/224846/1417?u=peter_richardson
